spring:
  application:
    name: PostsMS
  cloud: 
    consul:
      host: localhost
      discovery:
        hostname: localhost
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost/post_db
    username: root
    password: 
  jpa: 
    hibernate.ddl-auto: update
 
server:
  port: 2003
  
NO_POST_FOUND: No Post Found